[package]
description.workspace = true
edition               = "2024"
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
name                  = "swc_experimental_ecma_ast"
repository.workspace  = true
version               = "0.9.0"

[features]
shared_string_allocator = []

[dependencies]
num-bigint       = { workspace = true }
oxc_index        = { workspace = true }
unicode-id-start = { workspace = true }

swc_experimental_allocator  = { workspace = true }
swc_experimental_ast_macros = { workspace = true }
