name: Release Publish

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Release pull request number
        required: true
        type: number

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish crates
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout PR ref
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          ref: refs/pull/${{ inputs.pr_number }}/head

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@dc354b3df5a8e4db0bff5361fa176da74fcf3151 # v1v1

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces --locked

      - name: Authenticate to crates.io
        id: crates-io-auth
        uses: rust-lang/crates-io-auth-action@a1c979fa8eec9cf00f2c01904184fe133deb0ce9 # v1

      - name: Publish workspace crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.crates-io-auth.outputs.token }}
        run: |
          cargo ws publish --force "swc*" --publish-as-is
